### ISSUE TITLE
Bad checksum

### ISSUE THREAD

**Issue by Ramarti** [OpenZeppelin/accesscontrol-explorer#20]
When copy-pasting the addresses as seen in Access Control Explorer to use in ethers.js scripts, I keep getting error:

```
reason: 'bad address checksum',
code: 'INVALID_ARGUMENT',
```

**Comment by frangio** [comment]
There was a bug in our checksum function. Fixed in https://github.com/OpenZeppelin/accesscontrol-explorer/commit/1b6b0eaeeb696da5063609e0632ded09bea24571.
